# NOTE: update this with your service name
service: api-telos-net

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  bundle:
    linting: false
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-accounts
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  testnetRotationTableName: ${self:custom.stage}-testnet-rotation
  testnetFaucetTableName: ${self:custom.stage}-testnet-faucet
  testnetRotationTableThroughput: 5
  testnetFaucetTableThroughput: 5
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  environment:
    tableName: ${self:custom.tableName}
    testnetFaucetTableName: ${self:custom.testnetFaucetTableName}
    testnetRotationTableName: ${self:custom.testnetRotationTableName}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ AccountsTable, Arn ]
        - "Fn::GetAtt": [ TestnetRotationTable, Arn ]
        - "Fn::GetAtt": [ TestnetFaucetTable, Arn ]
    - Effect: Allow
      Action:
        - secretsmanager:Describe*
        - secretsmanager:Get*
        - secretsmanager:List
      Resource: "*"

functions:
  register:
    handler: register.main
    events:
      - http:
          path: v1/registrations
          method: post
          private: false
          cors: true

  create:
    handler: create.main
    events: 
      - http:
          path: v1/accounts
          method: post
          private: false
          cors: true

  keygen:
    handler: util.keygen
    events:
      - http:
          path: v1/keys
          method: get
          cors: true
          private: false

  exists:
    handler: util.checkAccount2
    events:
      - http:
          path: v1/accounts/{telosAccount}
          method: get
          cors: true
          private: false
  
  delete:
    handler: util.deleteRecord
    events:
      - http:
          path: v1/registrations
          method: delete
          cors: true
          private: false

  circulatingSupply:
    handler: chaininfo.circulatingSupply
    events:
      - http:
          path: v1/supply/circulating
          method: get
          private: false
          cors: true

  totalSupply:
    handler: chaininfo.totalSupply
    events:
      - http:
          path: v1/supply/total
          method: get
          private: false
          cors: true
  
  getTestnetRotation:
    handler: testnet.getRotationSchedule
    events:
      - http:
          path: v1/testnet/rotation_schedule
          method: get
          private: false
          cors: true

  rotateTestnet:
    handler: testnet.autorotate
    events:
      - http:
          path: v1/testnet/rotate
          method: get
          private: false
          cors: true

  addToRotation:
    handler: testnet.addToRotation
    events:
      - http:
          path: v1/testnet/produce/{bpAccount}
          method: get
          private: false
          cors: true

  testnetCreate:
    handler: testnet.account
    events: 
      - http:
          path: v1/testnet/account
          method: post
          private: false
          cors: true

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/dynamodb-testnet-tables.yml)}