apiVersion: v1
kind: Service
metadata:
  name: api-telos-net
  labels:
    app: fastify-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: fastify-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastify-api
  labels:
    app: fastify-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastify-api
  template:
    metadata:
      labels:
        app: fastify-api
    spec:
      containers:
        - name: api
          image: registry.gitlab.com/telosfoundation/api-telos-net/fastify-api:0.0.1
          ports:
            - containerPort: 3000
